### ISSUE TITLE
NORTH Container does not pass health check, Oasis fails to start.

### ISSUE THREAD

**Issue by altugyi** [PDI-Berlin/PDI-NOMAD-Oasis-image#1]
* `docker compose pull && docker compose up -d` results in:

```
[+] Running 8/8
 ✔ Network nomad_oasis_network     Created                                                                                                                                                                   0.0s 
 ✘ Container nomad_oasis_north     Error                                                                                                                                                                    19.3s 
 ✔ Container nomad_oasis_rabbitmq  Healthy                                                                                                                                                                   6.5s 
 ✔ Container nomad_oasis_elastic   Healthy                                                                                                                                                                  16.0s 
 ✔ Container nomad_oasis_mongo     Healthy                                                                                                                                                                   6.0s 
 ✔ Container nomad_oasis_worker    Started                                                                                                                                                                  16.1s 
 ✔ Container nomad_oasis_app       Healthy                                                                                                                                                                  81.7s 
 ✔ Container nomad_oasis_proxy     Created                                                                                                                                                                   0.0s 
dependency failed to start: container nomad_oasis_north is unhealthy
```
* What `docker logs nomad_oasis_north` gives:
```
2024-10-11 15:13:07 [warning  ] The following unsupported keys were found in your configuration, e.g. nomad.yaml: "enable".
ERROR: Failed to find specified config file: nomad/jupyterhub_config.py
```
* Changing the default group id `991` in the `docker-compose.yaml`'s `north` section with systems docker group id does not help.

**Comment by andreaa93** [comment]
Hi, maybe try to compose down, compose pull, and compose up again

**Comment by altugyi** [comment]
Tried several times and failed all the time on a Debian machine with fresh installation. Also tried in another Ubuntu machine, which failed also. Either I am doing something wrong or problem is with the image. Can you try to run locally?

Also do you know if I can pull a previous version of docker image from previous commits to try it out?

**Comment by andreaa93** [comment]
@ka-sarthak said that it happened to him and tried to rebuild the image and then went good. Could you give a try with this as well ?

**Comment by blueraft** [comment]
Hi, sorry this was an issue on our end. During the migration to the new distro mechanism, the develop image didn't have the jupyterhub config file. I have fixed and pushed a new `develop` image, so if you re-run the build step it should hopefully fix this issue.

Nevertheless I'd still recommend updating to the new distro template, which is more robust to a lot of these kind of errors and will avoid dependency issues in the future too.

**Comment by andreaa93** [comment]
Thank you very much @blueraft, will do

The way to update is manual update or is there some pull one can do?

**Comment by blueraft** [comment]
It's manual, the steps are listed here: https://github.com/FAIRmat-NFDI/nomad-distribution-template/releases/tag/v2.0.0

Let me know if you need any help!

**Comment by andreaa93** [comment]
Super, thank you!

**Comment by andreaa93** [comment]
@haltugyildirim try out the new image please

**Comment by altugyi** [comment]
Thank you @blueraft , it is fixed. Closing the issue.
